### ISSUE TITLE
Testing the hook that uses async / await

### ISSUE THREAD

**Issue by danzawadzki** [testing-library/react-hooks-testing-library#142] opened 2019-08-14 14:36 UTC
I created a custom react hook that is supposed to handle all less important api requests, which i don't want to store in the redux state. Hook works fine but I have trouble testing it. My test setup is jest and enzyme, but I decided to give a try **react-hooks-testing-library** here as well.

What I have tried so far is to first mock fetch request with a **fetch-mock** library, what works fine. Next, i render hook with `renderHook` method, which comes from react-hooks-testing-library. Unfortunately, looks like I do not quite understand the `waitForNextUpdate` method.

This is how my hook looks like.

**callApi method**
```ts
/**
 * Method to call api.
 *
 * @param {HttpMethod} method - Request type.
 * @param {string} path - Restful endpoint route.
 * @param {any} body - Request body data.
 */
export const callApi = async (method: HttpMethod, path: string, body: any = null) => {
	// Sends api request
	const response = await sendRequest(method, path, body);
	// Checks response and parse to the object
	const resJson = response ? await response.json() : '';

	if (resJson.error) {
		// If message contains error, it will throw new Error with code passed in status property (e.g. 401)
		throw new Error(resJson.status);
	} else {
		// Else returns response
		return resJson;
	}
};
```

**useApi hook**
```ts
export function useApi<R, B = undefined>(
	path: string,
	body: B | undefined = undefined,
	method: HttpMethod = HttpMethod.GET
): ResponseStatus<R> {
	const [response, setResponse] = useState();
	const [isLoading, setIsLoading] = useState<boolean>(false);
	const [error, setError] = useState<string | boolean>(false);

	useEffect(() => {
		const fetchData = async (): Promise<void> => {
			setError(false);
			setIsLoading(true);
			try {
				const result = await callApi(method, path, body);
				setResponse(result);
			} catch (errorResponse) {
				setError(errorResponse);
			}

			setIsLoading(false);
		};

		fetchData();
	}, [path, body, method]);

	return { response, isLoading, error };
}
```

Hook can take 3 different state combinations that I would like to test. Unfortunately, I have no idea how.

**Loading data:**
```
{ response: undefined, isLoading: true, error: false }
```

**Loaded data:**
```
{ response: R, isLoading: false, error: false }
```

**Error:**

```
{ response: undefined, isLoading: false, error: true }
```

This is how my test looks like at this moment:

```
import fetchMock from 'fetch-mock';
import { useApi } from './hooks';
import { renderHook } from '@testing-library/react-hooks';

test('', async () => {
	fetchMock.mock('*', {
		returnedData: 'foo'
	});

	const { result, waitForNextUpdate } = renderHook(() => useApi('/data-owners'));

	console.log(result.current);

	await waitForNextUpdate();

	console.log(result.current);
});
```

I reviewed a lot of articles on the medium and issues on github, but I still can't see where the problem may be.

**Comment by mpeyper** [comment] 2019-08-27 13:14
Hi @danzawadzki,

Sorry it's taken a while to get back to you.  Is this still causing you issues?  If so, what version of the `react`, `react-test-renderer` and `@testing-library/react-hooks` are you using?

What is the actual issue you are seeing?  Is `waitForNextUpdate` never resolving, or is it resolving and `result.current` is not waht you expect?

> Unfortunately, looks like I do not quite understand the `waitForNextUpdate` method.

All `waitForNextUpdate` does is return a promise that will resolve on the next render of the component that is wrapping your hook (`renderHook` creates this component for you).  If it's not resolving then it's because the componet has not rerendered.

**Comment by PolarbearDK** [comment] 2019-09-02 10:38
I am struggling with a similar issue.

react: 16.9.0
react-test-renderer: 16.9.0
@testing-library/react-hooks": 2.0.1

The problem is that the setResponse method after the await statement seems to be called (verified with console.log), but the state does not reflect this.

**Comment by mpeyper** [comment] 2019-09-05 13:37
I'm not able to reproduce the issue -> [sandbox](https://codesandbox.io/s/testing-custom-hook-demo-d6edf?fontsize=14&module=%2Fsrc%2FuseApi.test.js&previewwindow=tests)

I had some trouble getting fetch-mock to work in the codesandbox, so I hacked together my own (crude) version, as well as removed typescript to make building it a bit more straight forward, so it's not exactly replicating the scenario, but I don't believe it should affect the outcome of the tests.

As you can see, the test passes, asserting the response is the mocked value.  Am I missing something here?

**Comment by PolarbearDK** [comment] 2019-09-17 20:02
I just had time to look at the problem again.

It finally dawned on me that I was looking at a local version of state I had deconstructed from result.current.xxx. 

Once i used result.current it was working as expected.

**Comment by mpeyper** [comment] 2019-09-17 21:13
Great. I'll close this now.

**Closed by mpeyper** 2019-09-17 21:13 UTC
Labels: question
