### ISSUE TITLE
How to avoid waitForNextUpdate Catch-22

### ISSUE THREAD

**Issue by DaveStein** [testing-library/react-hooks-testing-library#84] opened 2019-06-03 14:15 UTC
It seems I can't properly test async situations, if values are sometimes cached. 

Let's say I check a value every minute. I keep it cached for five minutes. So in reality, I am making the async request every five minutes.

I have a helper method to test such things like this:

```
async function runEffects(wait = true) {
  const { result, waitForNextUpdate } = renderHook(() =>
    useActiveStream()
  );

  if (wait) {
    await waitForNextUpdate();
  }

  return {
    result
  };
}
```

In practice, I know to pass `true` for `wait` on the first try. Then on tries 2,3,4 to pass `false`. Then back to 5 I would pass `true`. This is assuming I am trying after running fake timers for a minute each time.

Here is the issue: If an XHR request gets made on the second try, my test will still pass since I am not waiting for update. Nothing will have been called when the code runs without the `await`. My first thought would be to always `await` to catch that, but obviously that would leave a promise that times out the test since when it's functional, there is no promise being resolved.

Is there a way around this?

**Comment by mpeyper** [comment] 2019-06-11 11:41
Hi @DaveStein,

Ideally, I'd like to have a `result.pending` property that is `true` if there are outstanding updated withing to resolve, but unfrotunately there is no predicatble way (that I know of) to add this feature.  The issue is that a hook can arbitrarily delay a `setState` call after an sync call (`setTimeout`, `promise.then`, callbacks, etc.) and `renderHook` has no idea that the calling hook has scheduled one of these updates.

An alternative approach might be to have `waitForNextUpdate` accept a timeout the rejects the promise if an update is not recieved by then, so you could write your test like:

```js
async function runEffects(wait = true) {
  const { result, waitForNextUpdate } = renderHook(() =>
    useActiveStream()
  );
  
  try {
    await waitForNextUpdate(100); // or some timeout high enough that an update should have happened by then
  } catch (e) {
    if (!wait) {
      throw e
    }
  }
  return {
    result
  };
}
```

This has the unfortunate effect of slowing down any test that that you expect not to actually wait as it has to wait the full length of the timeout to be sure it won't, plus the headaches you'll get from the speed of your dev machine vs someone elses vs the CI server (speaking from experience).  I've been thinking that this might be a useful feature for this library anyway, but I'm not sure it's quite right for your scenario.

I'm actually not sure the right answer here, but I feel like if your test is relying on the cache being hit or not, then injecting (and mocking?) that dependency into the hook, perhaps as a prop or using context, might be a more reliable approach.

I'm afraid I cannot give much more help without seeing the `useActiveStream` hook itself to get a better idea of how you can code around the limitations.

**Comment by mpeyper** [comment] 2019-06-19 13:48
Closing this for now.  Happy to reopen for more discussion in the future.

**Closed by mpeyper** 2019-06-19 13:48 UTC
Labels: question
