### ISSUE TITLE
renderhook doesn't read latest mocked implementation when working with multiple tests

### ISSUE THREAD

**Issue by poorvasingh04** [testing-library/react-hooks-testing-library#685] opened 2021-08-31 16:16 UTC
- `react-hooks-testing-library` version: 7.0.1
- `react` version: 16.13.1
- `react-native` version: 0.63.4
- `react-dom` version (if applicable):
- `react-test-renderer` version (if applicable):
- `node` version: 14.17.3
- `yarn` version: 1.22.10

### Relevant code or config:

This is my Test class where useService is a custom hook. 'module' is a custom third party framework.
```js
import {renderHook} from '@testing-library/react-hooks'
import {getService, mode} from 'module';
import {useService} from './index';

jest.mock('module', () => ({
  getService: jest.fn(() => ({
    getCapabilities: jest.fn(() => Promise.resolve({})),
}));

describe('module reports that mode is unsupported', () => {
    it('useService returns that device mode is not supported', async () => {
      // @ts-expect-error
      getService.mockImplementation(() => ({
        getCapabilities: () => Promise.resolve({
          mode: 'UNSUPPORTED'
        }),
      }));

      const {result, rerender} = renderHook(() => useService())
      expect(result.current).toMatchObject({
        deviceMode: false, isModeAuto: false // These values are returned from hook depending on input value of mode
      });
    });
  });
```

### What you did:

I am trying to test my custom hook- useService. 
This hook uses a custom module. I have mocked that in the test class. Everything works fine for single test. I need to change the mock implementation for second test. But seems like renderhook always reads mock declared at global level. 

### What happened:

Test fails

### Reproduction:

1. Create a custom hook
2. Use some framework that needs to be mocked and custom hook returns a value depending on this mock
3. Try to test different scenarios with different values in different tests

### Problem description:

I need to use different value of mock for different test and I expect renderhook to read latest mock value.

### Suggested solution:

Solutions I already tried -
1. rerender - It rerenders the hook but with old value of mock. 
2. getService.mockImplementation - when I print the value of properties after this line. It prints updated value but renderhook still returns the values mocked in global scope. Same with jest.spyOn method. 

So, I believe renderhook never reads latest mock value from mockImplementation.

**Comment by mpeyper** [comment] 2021-09-01 09:09
Hey @poorvasingh04, this sounds more like a mocking/import issue than anything wrong with our library.  Jest module mocking can be a dumpster fire at the best of times, and I'm not sure what is going wrong for you here as on the surface it looks fine to me (I'm not a heavy mock user though).

You may be more timely and better support in the [#help channel of the Testing Library Discord server](https://discord.gg/d8GB25rK).

**Comment by poorvasingh** [comment] 2021-09-01 09:56
@mpeyper Thanks for sharing the help channel. The problem is mock works fine but renderhook doesn't read this value. I don't know why. If I print the value before calling renderhook, it prints updated value. But somehow renderhook still reads value declared globally.

**Comment by mpeyper** [comment] 2021-09-01 09:58
My guess is the value it gets when it imports gets locked to the global one, so by the time you change it in the test, it's too late as the import has already occurred.  It's just a hunch though.

**Comment by poorvasingh** [comment] 2021-09-01 10:01
@mpeyper I think I agree with you but is there a way to fix it?

**Comment by mpeyper** [comment] 2021-09-01 10:05
I'm not sure, I've always struggled with module mocking. That's why I directed you to the help channel. I'm sure someone there can help out.

I also found [this on Stackoverflow](https://stackoverflow.com/a/45007792/6902543), might be helpful?

**Comment by poorvasingh** [comment] 2021-09-01 10:08
@mpeyper I posted it in channel. And I already tried these solution. Like I said, mockImplementation works fine but renderhook can't read it.

**Comment by mpeyper** [comment] 2021-09-01 10:12
I want to be clear, `renderHook` has no control over how node is importing or jest is mocking the module. Your issue is not with this library.

**Comment by poorvasingh** [comment] 2021-09-01 10:15
but jest mock works fine otherwise.

**Comment by mpeyper** [comment] 2021-09-01 10:52
I've just tried to replicate this locally (I made a few assumptions about what `useService` and `getService` were doing and the issue I ran into was not related to module mocking at all (it worked fine for me with the setup shown here), but rather the test was not waiting for the promise to resolve, so `result.current` contained the default `capabilities` state value.  Change the test like this allowed it to pass:

```ts
import { renderHook } from '../'
import { getService } from './service'
import { useService } from './example'

jest.mock('./service', () => ({
  getService: jest.fn(() => ({
    getCapabilities: jest.fn(() => Promise.resolve({}))
  }))
}))

describe('module reports that mode is unsupported', () => {
  it('useService returns that device mode is not supported', async () => {
    // @ts-expect-error
    getService.mockImplementation(() => ({
      getCapabilities: () =>
        Promise.resolve({
          mode: 'UNSUPPORTED'
        })
    }))

    const { result, waitForNextUpdate } = renderHook(() => useService())

    await waitForNextUpdate() // wait here for the promise to resolve

    expect(result.current).toMatchObject({
      deviceMode: false,
      isModeAuto: false // These values are returned from hook depending on input value of mode
    })
  })
})
```

**Comment by poorvasingh** [comment] 2021-09-01 11:27
It still fails for me. My hook hooks like this. Am I missing something here?

`import {
  getService,
} from 'service';

export interface Capabilities {
  deviceMode: string;
}

export const useService = () => {
  let capabilities: Capabilities;
  let lastDeviceMode: boolean = false;

  getService()
    .getCapabilities()
    .then(({contentSharing, deviceMode}) => {
      capabilities = {deviceMode};
    });

  return () => {
    const [isDeviceMode, setIsDeviceMode] = useState(lastDeviceMode);

    useEffect(() => {
      const deviceModeStatusListener: DeviceModeStatusListener = (isDeviceMode) => {
        setIsDeviceMode(isDeviceMode);
      };

      getService().registerDeviceModeStatusListener(deviceModeStatusListener);

      return () => {
        getContentIngestService().unregisterDeviceModeStatusListener(deviceModeStatusListener);
      };
    }, []);

    return {
      deviceMode: ['AUTOMATIC','MANUAL'].includes(capabilities?.deviceMode),
      isModeAuto: capabilities?.deviceMode ===' AUTOMATIC',
    };
  };
};`

**Comment by mpeyper** [comment] 2021-09-03 13:37
Sorry for te delay @poorvasingh, I got busy with work/life and there's a lot to unpack here.

Firstly, are you aware there is a space at the front of `AUTOMATIC` in 

```ts
isModeAuto: capabilities?.deviceMode === ' AUTOMATIC'
```

I'm assuming that is just a typo and not a big problem, just wanted to point it out just in case.

Right, so, what you are calling in your test (`useService()` is not a custom hook.  However, your `useService()` function is _returning_ a function that is a custom hook (see the `return () => { ...  }`).

I was able to get the your test to pass just by calling `renderHook(() => useService()())` (notice the double `()()`) and commenting out the calls to `registerDeviceModeStatusListener` and `unregisterDeviceModeStatusListener` (neither the global or local mocks were stubbing those out so they were just throwing undefined errors when called).

The only other explanation I can come up with, especially if you have other tests that are passing, is that somewhere outside this test you are calling the outer `useService` function to create the custom hook, something like

```ts
import {renderHook} from '@testing-library/react-hooks'
import {getService, mode} from 'module';
import {useService as createUseService} from './index';

jest.mock('./service', () => ({
  getService: jest.fn(() => ({
    getCapabilities: jest.fn(() => Promise.resolve({}))
  }))
}))

const useService = createUseService()

describe('module reports that mode is unsupported', () => {
  it('useService returns that device mode is not supported', async () => {
    // @ts-expect-error abc
    // eslint-disable-next-line @typescript-eslint/no-unsafe-call
    getService.mockImplementation(() => ({
      getCapabilities: () =>
        Promise.resolve({
          mode: 'UNSUPPORTED'
        })
    }))

    const { result } = renderHook(() => useService())
  
    // ...
  })
})
```

This would also explain why the global mocking was getting locked in by the time the test was run, because `getService().getCapabilities()` has already been called when creating the hook function.  This explanation feels unlikely though given the test snippet shared in the original message (I had to adjust the import to get this to run without a syntax error about the name `useService` already existing).

Overall, the hook function shared above is is quite strange.  The call to `getService().getCapabilities().then(...)`  is likely being a bit problematic for you as the promise updates the variable `capabilities` when it resolves, but that won't trigger a render with the new values as it's not calling a state setter.  In practice, this might not be an issue if `registerDeviceModeStatusListener` is pushing an update that sets the `isDeviceMode`, triggering a new render with the updated `capabilities` value, but `isDeviceMode` is not actually being used at all itself.

Another possible issue is in the `useEffect`, you are registering the device mode listener with `getService()`, but unregistering it with `getContentIngestService`.  These should probably be the same service, right?

Also, possibly and issue or possibly just some clever aliasing, but the `getService` imports are coming from different places:

1. `import { getService } from 'service'` in the hook file
2. `import { getService } from 'module'` in the test file

It could be nothing or it could be why it appears the mocking is not working (because it actually mocking the wrong thing).  All my local testing replace these aliases with relative paths to my local files, so I cannot confirm either way.

Finally, the `getService().getCapabilities().then({ contentSharing, deviceMode } => {...})` callback is referencing `deviceMode` (and the unused `contentSharing`), but the mocks in your tests are returning just `mode`:

```ts
getService.mockImplementation(() => ({
  getCapabilities: () => Promise.resolve({
    mode: 'UNSUPPORTED'
  }),
}));
```

For me, this actually didn't cause the test to fail as the values being checked in the return don't particularly mind if they are `'UNSUPPORTED'` or `undefined` to pass the assertion in the test:

```ts
return {
  deviceMode: ['AUTOMATIC', 'MANUAL'].includes(capabilities?.deviceMode),
  isModeAuto: capabilities?.deviceMode === ' AUTOMATIC'
}
```

It should probably be consistent though it more closely matches reality.

Personally, I think the hook function should look something more like:

```ts
export const useService = () => {
  const [capabilities, setCapabilaties] = useState<Capabilities>()
  const [isDeviceMode, setIsDeviceMode] = useState(false) // I'm still not sure what you want to do with isDeviceMode

  useEffect(() => {
    getService()
    .getCapabilities()
    .then(({ deviceMode }) => {
      setCapabilaties({ deviceMode })
    })
  }, [])

  useEffect(() => {
    getService().registerDeviceModeStatusListener(setIsDeviceMode)

    return () => {
      getService().unregisterDeviceModeStatusListener(setIsDeviceMode)
    }
  }, [])

  return {
    deviceMode: ['AUTOMATIC', 'MANUAL'].includes(capabilities?.deviceMode ?? ''),
    isModeAuto: capabilities?.deviceMode === ' AUTOMATIC'
  }
}
```

And the test would look like:

```ts
describe('module reports that mode is unsupported', () => {
  it('useService returns that device mode is not supported', async () => {
    // @ts-expect-error
    // eslint-disable-next-line @typescript-eslint/no-unsafe-call
    getService.mockImplementation(() => ({
      getCapabilities: () =>
        Promise.resolve({
          deviceMode: 'UNSUPPORTED'
        }),
      registerDeviceModeStatusListener: () => {},
      unregisterDeviceModeStatusListener: () => {},
    }))

    const { result, waitForNextUpdate } = renderHook(() => useService())

    await waitForNextUpdate()

    expect(result.current).toMatchObject({
      deviceMode: false,
      isModeAuto: false // These values are returned from hook depending on input value of mode
    })
  })
})
```

And then you should have a green test:

![image](https://user-images.githubusercontent.com/23029903/132013021-277344ba-50c0-454d-abe2-302f414e2ad7.png)

Obviously I've put loads of assumptions in here about your system, but hopefully it helps enough.

**Comment by poorvasingh** [comment] 2021-09-06 13:03
@mpeyper Thanks for the help. Some of the things in my above sample are typo because I renamed everything before sharing it here. 
What worked for me is moving getCapabilities code to useEffect.

**Comment by mpeyper** [comment] 2021-09-06 20:07
Is there anything else for this one then, or can we close it?

**Comment by poorvasingh** [comment] 2021-09-07 08:37
we can close it. Thank you 🙏

**Closed** 2021-09-07 08:51 UTC
Labels: question
